// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: distributions.proto

package distributions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributionResponse_Variant_VariantType int32

const (
	DistributionResponse_Variant_CONTROL   DistributionResponse_Variant_VariantType = 0
	DistributionResponse_Variant_TREATMENT DistributionResponse_Variant_VariantType = 1
)

// Enum value maps for DistributionResponse_Variant_VariantType.
var (
	DistributionResponse_Variant_VariantType_name = map[int32]string{
		0: "CONTROL",
		1: "TREATMENT",
	}
	DistributionResponse_Variant_VariantType_value = map[string]int32{
		"CONTROL":   0,
		"TREATMENT": 1,
	}
)

func (x DistributionResponse_Variant_VariantType) Enum() *DistributionResponse_Variant_VariantType {
	p := new(DistributionResponse_Variant_VariantType)
	*p = x
	return p
}

func (x DistributionResponse_Variant_VariantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionResponse_Variant_VariantType) Descriptor() protoreflect.EnumDescriptor {
	return file_distributions_proto_enumTypes[0].Descriptor()
}

func (DistributionResponse_Variant_VariantType) Type() protoreflect.EnumType {
	return &file_distributions_proto_enumTypes[0]
}

func (x DistributionResponse_Variant_VariantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionResponse_Variant_VariantType.Descriptor instead.
func (DistributionResponse_Variant_VariantType) EnumDescriptor() ([]byte, []int) {
	return file_distributions_proto_rawDescGZIP(), []int{1, 0, 0}
}

// The request message containing user properties
type DistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExperimentId   string   `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	UserId         string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string   `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Latitude       *float64 `protobuf:"fixed64,4,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude      *float64 `protobuf:"fixed64,5,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
}

func (x *DistributionRequest) Reset() {
	*x = DistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionRequest) ProtoMessage() {}

func (x *DistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distributions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionRequest.ProtoReflect.Descriptor instead.
func (*DistributionRequest) Descriptor() ([]byte, []int) {
	return file_distributions_proto_rawDescGZIP(), []int{0}
}

func (x *DistributionRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *DistributionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DistributionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DistributionRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *DistributionRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

// The response message containing the variant assignment
type DistributionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignedVariant        *DistributionResponse_Variant `protobuf:"bytes,2,opt,name=assigned_variant,json=assignedVariant,proto3" json:"assigned_variant,omitempty"`
	ExcludedFromExperiment bool                          `protobuf:"varint,3,opt,name=excluded_from_experiment,json=excludedFromExperiment,proto3" json:"excluded_from_experiment,omitempty"`
}

func (x *DistributionResponse) Reset() {
	*x = DistributionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionResponse) ProtoMessage() {}

func (x *DistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distributions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionResponse.ProtoReflect.Descriptor instead.
func (*DistributionResponse) Descriptor() ([]byte, []int) {
	return file_distributions_proto_rawDescGZIP(), []int{1}
}

func (x *DistributionResponse) GetAssignedVariant() *DistributionResponse_Variant {
	if x != nil {
		return x.AssignedVariant
	}
	return nil
}

func (x *DistributionResponse) GetExcludedFromExperiment() bool {
	if x != nil {
		return x.ExcludedFromExperiment
	}
	return false
}

type DistributionResponse_Variant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type DistributionResponse_Variant_VariantType `protobuf:"varint,2,opt,name=type,proto3,enum=distributions.DistributionResponse_Variant_VariantType" json:"type,omitempty"`
}

func (x *DistributionResponse_Variant) Reset() {
	*x = DistributionResponse_Variant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distributions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributionResponse_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionResponse_Variant) ProtoMessage() {}

func (x *DistributionResponse_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_distributions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionResponse_Variant.ProtoReflect.Descriptor instead.
func (*DistributionResponse_Variant) Descriptor() ([]byte, []int) {
	return file_distributions_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DistributionResponse_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DistributionResponse_Variant) GetType() DistributionResponse_Variant_VariantType {
	if x != nil {
		return x.Type
	}
	return DistributionResponse_Variant_CONTROL
}

var File_distributions_proto protoreflect.FileDescriptor

var file_distributions_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x22, 0xc0, 0x02, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x10, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x52, 0x0f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x95, 0x01,
	0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a, 0x0b, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x52, 0x45, 0x41, 0x54, 0x4d,
	0x45, 0x4e, 0x54, 0x10, 0x01, 0x32, 0x74, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x63, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4b, 0x42, 0x12, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x6c, 0x75, 0x77, 0x61, 0x74, 0x6f, 0x62, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x64,
	0x65, 0x6d, 0x6f, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distributions_proto_rawDescOnce sync.Once
	file_distributions_proto_rawDescData = file_distributions_proto_rawDesc
)

func file_distributions_proto_rawDescGZIP() []byte {
	file_distributions_proto_rawDescOnce.Do(func() {
		file_distributions_proto_rawDescData = protoimpl.X.CompressGZIP(file_distributions_proto_rawDescData)
	})
	return file_distributions_proto_rawDescData
}

var file_distributions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distributions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_distributions_proto_goTypes = []interface{}{
	(DistributionResponse_Variant_VariantType)(0), // 0: distributions.DistributionResponse.Variant.VariantType
	(*DistributionRequest)(nil),                   // 1: distributions.DistributionRequest
	(*DistributionResponse)(nil),                  // 2: distributions.DistributionResponse
	(*DistributionResponse_Variant)(nil),          // 3: distributions.DistributionResponse.Variant
}
var file_distributions_proto_depIdxs = []int32{
	3, // 0: distributions.DistributionResponse.assigned_variant:type_name -> distributions.DistributionResponse.Variant
	0, // 1: distributions.DistributionResponse.Variant.type:type_name -> distributions.DistributionResponse.Variant.VariantType
	1, // 2: distributions.Distributions.GetVariantDistribution:input_type -> distributions.DistributionRequest
	2, // 3: distributions.Distributions.GetVariantDistribution:output_type -> distributions.DistributionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_distributions_proto_init() }
func file_distributions_proto_init() {
	if File_distributions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_distributions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distributions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributionResponse_Variant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_distributions_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distributions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distributions_proto_goTypes,
		DependencyIndexes: file_distributions_proto_depIdxs,
		EnumInfos:         file_distributions_proto_enumTypes,
		MessageInfos:      file_distributions_proto_msgTypes,
	}.Build()
	File_distributions_proto = out.File
	file_distributions_proto_rawDesc = nil
	file_distributions_proto_goTypes = nil
	file_distributions_proto_depIdxs = nil
}
